# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kollect-col

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: node:22-bullseye
    steps:
      - uses: actions/checkout@v4

      - name: Install zip
        run: apt-get update -y && apt-get install -y zip

      - name: Install dependencies
        run: npm install

      - name: Build client and server
        run: npm run build

      - name: Create deployment zip
        run: |
          zip -r release.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "docs/*" \
            -x "*.db" \
            -x "*.db-shm" \
            -x "*.db-wal"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kollect-col'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F377F502F618411F80E6661C2CBF7723 }}
